### ISSUE TITLE
Playlists from backend?

### ISSUE THREAD

**Issue by iantrich** [fondberg/spotify-card#2]
Have you thought about creating a component to handle the backend stuff? I would prefer that over having the frontend call Spotify direclty for all instances of my frontend

**Comment by fondberg** [comment]
I have not, because that would be like proxying the same calls. What would be the benefit of that?

**Comment by iantrich** [comment]
The idea of having state in the state machine (i.e. the available playlists) as that would allow other things, even automations to use them. Maybe I'll look into it in the future as that could be pretty useful.
